default:
	g++ scheduling.cpp -std=c++11 -Wall -Wextra -Werror -pedantic -o run
	./run < input.txt
simple:
	g++ scheduling.cpp -std=c++11 -o run
	./run < input.txt
go:
	./run < input.txt
clean:
	rm run
